### ISSUE TITLE
Predict future values with PolynomialNode

### ISSUE THREAD

**Issue by abourdon** [datathings/greycat#84]
Hi,

I'm looking for a way to predict future values based on a `PolynomialNode`.

I mean, given:
```java
final Graph g = new GraphBuilder().withPlugin(new MLPlugin()).build();
g.connect(isConnected -> {
    final PolynomialNode node = (PolynomialNode) g.newTypedNode(0, 0, PolynomialNode.NAME);
    IntStream
            .range(0, 11) // from 0 to 10 (11 excluded)
            .filter(step -> step % 2 == 0) // only take even numbers
            .forEach(step -> node.travelInTime(
                    step,
                    polynomial -> polynomial.set(PolynomialNode.VALUE, Type.DOUBLE, step * 2.0)) // should define the 0.0+2.0*t polynomial
            );
    node.travelInTime(5, polynomial -> System.out.println(polynomial.get(PolynomialNode.VALUE))); // prints 10.0 as expected
    node.travelInTime(30, polynomial -> System.out.println(polynomial.get(PolynomialNode.VALUE))); // actually prints 20.0 but wanted to be 60.0
});
```

I would like that the last line
```java
    node.travelInTime(30, polynomial -> System.out.println(polynomial.get(PolynomialNode.VALUE)));
```
gives me `60.0`, instead of `20.0`.

It appears predictions are only valid within the known time range (0 to 10 in our example), as I can see in the first travel in time
```java
   node.travelInTime(5, polynomial -> System.out.println(polynomial.get(PolynomialNode.VALUE)));
```
that prints me `10.0` as expected.

Indeed, any time travels more high than the last known time (here 10) seem to give the last known computed value (here `20.0`).

How can I predict future values, i.e., by traveling a future time, with a `PolynomialNode`?

Thanks,
Aurélien

**Comment by assaad** [comment]
Hello, 
The purpose of the polynomial node, was to extrapolate the missing data in between known points. 
so if you have time 0,4,7,9,12, the polynomial node will extrapolate anything in between. You can query it from 0 to 12. outside the range, it doesn't extrapolate, and returns by default the last known value (in your case it's returning the last value stored at 10 which is 20).
However we can enable extrapolation on the whole range, if you need it, not a problem. 
Another point btw (since we lack documentation for now) it's better to set a precision on the polynomial node, and a maximum degrees.
